### ISSUE TITLE
Use an alternative ci workflow that does not require using Generate-DockerImageVariants module

### ISSUE THREAD

**Issue by joeltimothyoh** [theohbrothers/Generate-DockerImageVariants#57]
As described, until we are settled on the conventions that should be adopted across our docker image repositories.

**Comment by leojonathanoh** [comment]
renamed the issue.

**Comment by leojonathanoh** [comment]
Currently, the workflow for all our `theohbrothers/docker-<binary>` repos using `Generate-DockerImageVariants` module include important aspects of a good OSS project, see: https://github.com/startersclan/docker-steamcmd/pull/8#issuecomment-950419266
- docker build tests in PR
- docker build / push on `master`
- changelog generator https://github.com/startersclan/docker-steamcmd/pull/8#issuecomment-950651836
- automatic releases for semver / calver

Whereas repos such as `startersclan/docker-steamcmd` which do not use it are missing those very aspects, see https://github.com/startersclan/docker-steamcmd/issues/10 .

**Comment by leojonathanoh** [comment]
@joeltimothyoh For log retention for GHW, see https://github.com/startersclan/docker-steamcmd/issues/10#issuecomment-955209306.

As of this writing, log retention is limited to 90 days for all public repos regardless of github subscription.

I’m not sure if it is fair to preclude GHW as a CI provider based on the reason of poor log retention alone. Here’s some links that AZP is going to be succeeded by GHW:
- https://www.reddit.com/r/AZURE/comments/q3c029/are_azure_pipelines_being_pushed_to_the_side/

**Comment by joeltimothyoh** [comment]
The lack of log retention removes transparency and traceability in OSS projects and is alone sufficient reason for not using a CI provider. Most other providers don’t toy with the logs the way GHA or azp which it’s based off does. Just even begin imagining using GitLab CI/CD with expiring logs and see where you get with long-term infrastructure.

**Comment by leojonathanoh** [comment]
@joeltimothyoh what about all of the other open source projects, they will suffer the same issue if they use GHW. But i think because open source generally moves fast, log retention isn't very important. Log retention is generally more important for CD, not so much for CI.

**Comment by joeltimothyoh** [comment]
I think we can agree on the reasons for moving *fast*. @leojonathanoh

**Comment by joeltimothyoh** [comment]
I think we agree on why they move *fast*. @leojonathanoh

**Comment by leojonathanoh** [comment]
it's a mentality i guess. but for GHW to use this as an excuse for not supporting OSS with greater log retention, is rather sad
